### ISSUE TITLE
Purchase domain name and connect to the website

### ISSUE THREAD

**Issue by rpruim** [integrated-ethics/web#11]
Currently under consideration:

* integratedethics.org
* integratedethicslabs.org

Note, if we go with the former, the URL for the labs would likely be

* integratedethics.org/labs

**Comment by LoriCarter** [comment]
Catherine, Paul, and I like integratedethicslabs.org because we think it immediately points to science/tech

**Comment by rpruim** [comment]
Keep in mind that if we get `integaratedethics.org`, we can do things like

* `labs.integratedethics.org`
* `integratedethics.org/labs`

I'm still going back and forth on this one.

**Comment by rpruim** [comment]
It looks like `integratedethicslabs.com` and `integratedethicslabs.org` are both available.  .com is actually a touch cheaper.  We can grab either one for 10 years for approx. $100 at namecheap ($80 for .com and $116 for .org).  Do we have a preference between the two?

Looks like email forwarding is free and netlify handles SSL.

**Comment by ccrocke1** [comment]
Thank you for looking into this. I like either one.

**Comment by LoriCarter** [comment]
I'd probably choose .org. The .com sounds like a business!

**Comment by rpruim** [comment]
We are live at https://integratedethicslabs.org/

I may need to reconfigure it, however.  Netlify recommends using their DNS, but if I do that, it looks like namecheap can't/won't allow us to set up email aliases.  So I may need to convert back to using the namecheap domain name servers.

**Comment by rpruim** [comment]
I found a free service that provides email forwarding using netlify's DNS: 

* https://app.improvmx.com/domains/integratedethicslabs.org/dns

I've set up a few aliases, including `info@` (@LoriCarter and @ccrocke1) and `webmaster@` (@rpruim).  I'll send a test email shortly.

Let me know if there are other alias we want and where they should forward.

**Comment by rpruim** [comment]
It would probably be a good idea to have at least one more person able to access namecheap.  The instructions for sharing admin duties are at https://www.namecheap.com/support/knowledgebase/article.aspx/192/46/how-do-i-share-access-to-my-domain-with-other-users/.  The first step is for the other admin(s) to create an account at namecheap.  If you want to be one of the admins, let me know once you have an account.  (Note: There will likely be very little that needs doing since I have purchased the name for 10 years.  As long as we don't need to change the configuration, this should just run merrily along.)
