### ISSUE TITLE
Landing page "readme" text

### ISSUE THREAD

**Issue by kcarnold** [integrated-ethics/web#3]
It's currently Lorem Ipsum.

I think @LoriCarter has something written.

**Comment by LoriCarter** [comment]
The introduction I wrote is in the shared drive. I did not put it into a sub-folder, but it is finished as far as I am concerned

**Comment by paulschmelzenbach** [comment]
Added Lori's content to landing page

**Comment by rpruim** [comment]
I'm not sure whether that belongs there or not.  I had already dropped it here: https://wonderful-fermi-8c4db8.netlify.app/labs/intro-to-labs/ -- ~~but that seems to have gone away~~ (my bad, I missed a file in the commit process).

We have some things to figure out about the site organization, but I'm not sure that a detailed description of what is in the labs, how to use them, and an overview of the structure is what we want on the main landing page.  I'm not exactly sure what we do want on the landing page, but I'm thinking less detail and an invitation to other parts of the site.  An image would be good too, but I'm not sure what image.

We also have a placeholder for an about page.  For now, I basically dropped in all of our names with a 2-sentence opener.  That probably needs some rethinking as well.  I'm hoping to add an email address (or several) as contact info as well once we have our domain up and running.

**Comment by rpruim** [comment]
Closing in favor of #19.
