### ISSUE TITLE
Approve web version of "first look" lab

### ISSUE THREAD

**Issue by rpruim** [integrated-ethics/web#39]
This was mostly a reformatting.

Questions:
* [ ] In the list of virtues, a couple seem out of place: Provide for others, Sustainability.  I know what is meant, but they don't feel like character traits the way the others on the list do.  For most, you can fill in the blank: How does person X demonstrate their _____.  The blank doesn't work for these two.
* [ ] Also, I think this list doesn't match the list on the virtue ethics sheet, should it?

**Comment by LoriCarter** [comment]
I added Rebecca as an author. Otherwise, looks good.
