### ISSUE TITLE
Approve web version of open source accessibility lab

### ISSUE THREAD

**Issue by rpruim** [integrated-ethics/web#42]
Notes:
* Reading assignment and group discussion are separate items
* I created a short code for the virtues list, so we can easily place that list on any page and any edits to the list will affect all the pages where it appears.
* I removed some of the scaffolding for the assignment questions.
* I numbered the questions to be answered.  I think this makes it easier to locate them (and to avoid missing one).

**Comment by ccrocke1** [comment]
Looks good!
