### ISSUE TITLE
Approve web version of hospitable code lab

### ISSUE THREAD

**Issue by rpruim** [integrated-ethics/web#43]
I did a bit more editing of this one to
* make the flow and instructions clearer (at least to me)
* take advantage of the web format (tabsets for different programming languages, for example)
* make it clearer that the two versions are mainly about whether students have the code in electronic form or not.
* eliminate the instruction to "paste code below".  I'm not sure where that was to be, but there isn't a place to paste code in the lab currently.  (We could add some comments about collecting code from students, if we think that is desirable, but then we should include something in the instructor guide that says what we have in mind to do with it.)

**Comment by ccrocke1** [comment]
The handout was created for a completely online version of the course.  The instruction for "paste code below" (I believe) was just to ask students submit a copy of their improved code in a discussion post -like setting (for us- we use the discussion/ peer review feature in our LMS).

Edits look good.
