### ISSUE TITLE
Approve web version of avoiding algorithmic bias

### ISSUE THREAD

**Issue by rpruim** [integrated-ethics/web#44]
I found this one a bit confusing, especially when trying to just scan it and figure out what the outline was.  This one should be checked a bit more carefully to make sure I haven't messed anything up.

* There is an "alternative online" version, but (a) I don't see what it is alternative to nor why it needs to be online.  I've just made that the main worksheet.
* The worksheet only had 2 of the 3 scenarios from the instructor guide (numbered 1 and 3, but with the numbering not matching the instructor guide).  I added the third one.  **Was there a reason for the mismatch?**
* I've numbered all of the questions consecutively rather than restarting in each block.  It is confusing to have 5 number 1's on the same sheet.
* The worksheet didn't feel like it stood alone very well.  Even just adding in some headers and a small amount of guiding text, and relocating a few things seems to help, I think.

Also

* Rather than instruct instructors to make slides, I just made them and created a link.  It is easy to create HTML slides in RMarkdown.

* I'm not a fan of the "definition" of AI that is provided.
    > a system’s ability to correctly interpret external data, to learn from such data, and to use those learnings to achieve specific goals and tasks through flexible adaptation.

    Can we find a better one?  Without context, this seem like just bunch of fluffy words.  Do systems *interpret*? What does it mean to *learn*? What makes data *external*? What sort of *adaptation*? etc., etc.  To me this seems like a non-technical over-personification of what is going on and would not be useful for distinguishing something that is AI from something that is not.

* I wonder if the emphasis on *AI* is important here or not.  I'm guessing many universities might come up with there point-based systems based on basic generalized linear models rather than fancy AI algorithms (does anyone know?) In any case, the points here are not specific to AI really (well, perhaps that depends on how broadly you define AI).

    This is perhaps a tic of mine, but I see lots of places where people use AI and ML in inappropriate ways based on the non-technical meanings of the words involved (intelligence and learning), when it isn't clear that either of those (in the sense that they apply to people) is involved.

    Would it make more sense to focus on *clustering* or *ranking* or *rating*?  That's what these algorithms do, they cluster students into admitted and non-admitted, or rank them so that the top portion can be admitted (and perhaps portions of the list can get special bonuses, like scholarships).

**Comment by LoriCarter** [comment]
Randy,
Sorry for the confusion here. The online version was meant as a stand-alone assignment if the module could not be completed in a live class. We should have removed it. The only thing that students need if the module is done in class is a copy of the scenario assigned to their group. Other things, as you noted, are redundant. 

If you want to find a better defniition of AI, feel free. It made sense to me. 

This lab was very much based on the Weapons of Math Destruction book and so I sort of followed the language that I found there.

**Comment by LoriCarter** [comment]
This is definitely an example of "I wrote it so it makes sense to me!" Thank you for checking it. The flow should be 
Class discussion on college entrance algorithm
Students go to groups and discuss what went wrong in their scenario and why it went wrong
Students come back to class and look through EU guidelines as a class
Students go back to group and discuss either college admissions scenario or their group scenario in light of the EU guidelines - would one of them have helped avoid the problem?
Students come back to class and share their EU-scenario ideas with the class
Students discuss which framework EU guidelines support (deontology) - reinforces using one of the tools

Hope that helps!!

**Comment by rpruim** [comment]
So how does my version of things look to you?

**Comment by LoriCarter** [comment]
The main lab part looks good. The student handout should be reduced to the three scenarios and perhaps the EU guidelines. The rest is redundant.

**Comment by rpruim** [comment]
Looking for a definition of AI could lead to an infinite search.  But here is an interesting post: https://www.forbes.com/sites/bernardmarr/2018/02/14/the-key-definitions-of-artificial-intelligence-ai-that-explain-its-importance/?sh=6bef5584f5d8

**Comment by rpruim** [comment]
I would suggest leaving the "redundant stuff".  It is only redundant if the instructor follows the pre-activity flow in the guide, and even then it doesn't hurt to have those initial questions even if students already discussed them before getting the handout.  Besides, deletion is the easiest kind of edit.

Perhaps I'll make a separate version that just has the three scenarios for instructors who want to direct the flow of the conversation themselves rather than to have the questions on the worksheet.

**Comment by rpruim** [comment]
I've added this not to instructors:

> **Note to instructor**: Definition of AI. There are some weaknesses to the definition of AI given by 
Kaplan and Haenlein. In particular, many of the terms used in the definition do not have self-evident meanings, so it would probably be difficult to use this definition to decide whether something is or is not an example of AI. Try not to focus on the issue of defining AI -- keep the focus on the scenarios and the ethical issues they raise.

I'd still like to see a better definition of AI, but I think it is even more important that this lab does not bog down on the definition.
