### ISSUE TITLE
Should we post our "wish list" of labs that we brainstormed but are not begin actively developed yet?

### ISSUE THREAD

**Issue by rpruim** [integrated-ethics/web#51]
We have a list (see #10, for example).  We could add these to our /labs-overview/ page (noting their status) to give people a sense for what might still come.  Or we can keep that list to ourselves or only reveal portions of it (perhaps things we are more committed to making happen in the next ~ 1 year).

Thoughts, anyone?

**Comment by ccrocke1** [comment]
I think your second suggestion- reveal portions of our wish list, as we see things unfold is the way to go.  Only list items we are more committed to making happen in the next year.

**Comment by rpruim** [comment]
That seems like a reasonable approach.  Next question: Which future labs are we willing to list?  I suggest we create an issue for each lab we are planning to create and assign a person or people to it.  That will help us track progress.

**Comment by ccrocke1** [comment]
Since we need more data science & I plan on working on these by this fall-
if no one else has:

group work

data viz, probability & ethics, survey design, understanding data
provenance, etc.

**Comment by ccrocke1** [comment]
one more thought- we have engineering listed on the website- I would like
to get more up specifically for engineering ( not just software
engineering).
I do hope to help folks at PLNU ( or open to anyone else) write these, but
I don't think I can do these on my own - it is way outside of my wheelhouse.

**Comment by rpruim** [comment]
Regarding your list above:

* group work: I think @stacyderuiter expressed interest
* viz: I think @kcarnold  and I are interested in this.  (As might be a colleague of ours who is designing a data viz course for the MBA program at Calvin)
* probability and ethics: I'm teaching the first half of our prob/stats 2-semester sequence this fall, so this will be on my mind.  I've already reached out to Rebecca about this as well.

**Comment by rpruim** [comment]
I'll take care of adding these to our lab-overview.

**Comment by rpruim** [comment]
I've added some labs to the overview.  I'm going to close this, but @ccrocke1, if you can write a blurb for the data provenance lab, I'll add that one as well (or you can add it yourself -- just mimic the others).
